### ISSUE TITLE
Advantages over backing up folders manually?

### ISSUE THREAD

**Issue by mdhoney** [borgbackup/borg-import#46]
Your new tool seems to have been sent from heaven!  I am just in the process of offloading some BackInTime (rsync + hardlinks) backups (on a laptop) to Borg on a NAS.
So far I had been doing this manually, for example:
`borg create --stats --progress ::20200531-032853-565 20200531-032853-565`
for each of the timestamped directories.

If I use borg-import on the root folder, what will I gain over my more manual method?  Can I tell borg-import to only import a subset of these snapshots?

Anyway thanks, great work @ThomasWaldmann!

**Comment by ThomasWaldmann** [comment]
If you do it manually, please note that you may give some `--timestamp` (or so) option, if you want to replicate given timestamps.

borg-import isn't quite new, exists since quite a while. in fact relatively long, so i do not remember all the details and would have to read the source again. :-)

if you understand python, it might be quicker if you read it yourself (if the docs do not answer your questions).

**Comment by ThomasWaldmann** [comment]
OK, I've read a bit in the source now anyway and will update the readme with some advantages.
